### ISSUE TITLE
Trailing zeroes

### ISSUE THREAD

**Issue by Genbox** [Bulat-Ziganshin/FARSH#4]
In farsh.c, you have the following code:

```c
while (bytes >= STRIPE)
{
	size_t chunk = STRIPE;
	uint64_t h = farsh_full_block((const uint32_t*)ptr, key_ptr);
	sum = farsh_combine(sum, h);
	ptr += chunk;  bytes -= chunk;
}
if (bytes)
{
	size_t chunk = bytes;
	uint64_t h = farsh_partial_block((const uint32_t*)ptr, chunk, key_ptr);
	sum = farsh_combine(sum, h);
	ptr += chunk;  bytes -= chunk;
}
return farsh_final(sum) ^ key_ptr[bytes%STRIPE_ELEMENTS];   /* ensure that zeroes at the end of data will affect the hash value */
```
If we focus on the last line, it seems you want to XOR the results with one of the keys, at the position of 'bytes' (trimmed to STRIPE_ELEMENTS), but since you just set bytes to 0, it will always use the first key, making the key used independent of the number of bytes.

Maybe the last line of `ptr += chunk;  bytes -= chunk;` is not supposed to be there? there is no sense in incrementing the ptr as the value is not used after the increment, and reducing bytes, with bytes, is the same as setting it to 0.

Removing the line would make the algorithm length dependent, and make it use a different key based on the remaining length.

**Comment by Bulat-Ziganshin** [comment]
you are right. probably it was correct at the first time, and later copy-pasting broked it. thanks!

that said, now i don't consider farsh as good hash due to its construction. i think that hashes that sequentially update state with input wirds, are less vulnerable to changes in input data that compensate each other in their effect on final hash value

**Comment by rurban** [comment]
In smhasher this is called AppendedZeroes, which it fails. Therefore it is considered insecure. The collision attack is simple by just adding a random number of \0 to your keys.
